### ISSUE TITLE
testing on new input

### ISSUE THREAD

**Issue by mahilaMoghadami** [rsinghlab/pyaging#4]
hello
Dear Dennis,I've just came up with your research while researching about BioAge estimation. This is a very well-done research with a strong scientific base. It opens many new opportunities for application in medicine. 
but I don't know how to use your code in my new input value?
Is it any notebook available to understand how to use it?
or any readme file or other way you think it may help me.

thank you

**Comment by lcamillo** [comment]
Hello! Please find tutorials on how to apply `pyaging `to your own data in the documentation page: [https://pyaging.readthedocs.io/en/latest/](https://pyaging.readthedocs.io/en/latest/).
